server:
    port: 8080
spring:
    application:
        name: spring-data-exercise-1
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                show_sql: true
                format_sql: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yavuz_spring?useSSL=false
        username: yavuz
        password: p@ssw0rd

